### ISSUE TITLE
module 'asyncio' has no attribute 'timeout'

### ISSUE THREAD

**Issue by orlean24** [themiralay/getgrass-bot#1]
Hey, thanks for your work! 
With HTTP proxy in format: d1b88fee-8078-46bc-aaed-df7196183f5f==http://name:pass@proxy.com:8080 always :  Socket error: 410: Gone
Without proxy, no problem.

**Comment by themiralay** [comment]
Pay attention to the spaces
the list should always start with your user id. And it should be in the format .
`d1b88fee-8078-46bc-aaed-df7196183f5f==socks5://proxy.com:1080`
Don't ignore the possibility of a GetGrass ban.
